openapi: 3.0.0
info:
  title: 顔フィルター共有アプリ API
  version: '1.0.0'
  description: Firebase Authentication による認証付き顔フィルター共有アプリのAPI仕様

servers:
  - url: http://localhost:8080/api
    description: ローカルAPIサーバー

tags:
  - name: USER
    description: ユーザーに関する操作
  - name: FILTER
    description: 顔フィルターに関する操作

components:
  securitySchemes:
    FirebaseAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        nickname:
          type: string
          maxLength: 30
        avatarUrl:
          type: string
          format: uri
          nullable: true
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    FilterParameters:
      type: object
      required: [brightness, skin, contour, eye, nose, mouth]
      properties:
        brightness: { type: integer, minimum: 0, maximum: 100 }
        skin: { type: integer, minimum: 0, maximum: 100 }
        contour: { type: integer, minimum: 0, maximum: 100 }
        eye: { type: integer, minimum: 0, maximum: 100 }
        nose: { type: integer, minimum: 0, maximum: 100 }
        mouth: { type: integer, minimum: 0, maximum: 100 }

    Filter:
      allOf:
        - $ref: '#/components/schemas/FilterParameters'
        - type: object
          properties:
            id:
              type: string
              format: uuid

security:
  - FirebaseAuth: []

paths:
  /users:
    put:
      tags: [USER]
      summary: ユーザー登録
      security:
        - FirebaseAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [nickname]
              properties:
                id:
                  type: string
                  format: uuid
                nickname:
                  type: string
                  maxLength: 30
                avatarUrl:
                  type: string
                  format: uri
                  nullable: true
                FilterParameters:
                  $ref: '#/components/schemas/FilterParameters'
      responses:
        '201':
          description: ユーザー登録/更新成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  nickname:
                    type: string
                    maxLength: 30
                  avatarUrl:
                    type: string
                    format: uri
                    nullable: true
                  FilterParameters:
                    $ref: '#/components/schemas/FilterParameters'
                  createdAt:
                    type: string
                    format: date-time
                  updatedAt:
                    type: string
                    format: date-time
        '400':
          description: リクエスト形式不正
        '401':
          description: 認証エラー

  /users/list:
    get:
      tags: [USER]
      summary: ユーザー一覧取得
      security:
        - FirebaseAuth: []
      responses:
        '200':
          description: ユーザー一覧
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uuid
                    nickname:
                      type: string
                      maxLength: 30
                    avatarUrl:
                      type: string
                      format: uri
                      nullable: true
                    FilterParameters:
                      $ref: '#/components/schemas/FilterParameters'
                    createdAt:
                      type: string
                      format: date-time
                    updatedAt:
                      type: string
                      format: date-time
        '401':
          description: 認証エラー

  /users/me:
    get:
      tags: [USER]
      summary: 自分のユーザー情報取得
      security:
        - FirebaseAuth: []
      responses:
        '200':
          description: 自分のユーザー情報
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  nickname:
                    type: string
                    maxLength: 30
                  avatarUrl:
                    type: string
                    format: uri
                    nullable: true
                  FilterParameters:
                    $ref: '#/components/schemas/FilterParameters'
                  createdAt:
                    type: string
                    format: date-time
                  updatedAt:
                    type: string
                    format: date-time
        '401':
          description: 認証エラー

  /filters/{userId}:
    get:
      tags: [FILTER]
      summary: 指定ユーザーのフィルター取得
      security:
        - FirebaseAuth: []
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: 指定ユーザーのフィルター情報
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Filter'
        '401':
          description: 認証エラー
        '404':
          description: フィルターが見つかりません
